sudo: required
services:
    - docker

before_install:
    - docker build -t vinodres/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true vinodres/react-test npm test

after_success:
    - docker build -t vinodres/multi-client ./client
    - docker build -t vinodres/multi-nginx ./nginx
    - docker build -t vinodres/multi-server ./server
    - docker build -t vinodres/multi-worker ./worker
    #Login to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #Take these images and push them to docker hub
    - docker push vinodres/multi-client
    - docker push vinodres/multi-ngnix
    - docker push vinodres/multi-server
    - docker push vinodres/multi-worker