sudo: required
services:
    - docker

before_install:
    - docker build -t vinodres/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true vinodres/react-test npm test

after_success:
    - docker build -t vinodres/multi-client ./client
    - docker build -t vinodres/multi-nginx ./nginx
    - docker build -t vinodres/multi-server ./server
    - docker build -t vinodres/multi-worker ./worker
    #Login to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #Take these images and push them to docker hub
    - docker push vinodres/multi-client
    - docker push vinodres/multi-nginx
    - docker push vinodres/multi-server
    - docker push vinodres/multi-worker
deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env-1
    bucket_name: elasticbeanstalk-us-east-2-440804845544
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
